#!/bin/bash
## Set the location of the Vargo repository
## DIR=$HOME # Mine is in my home directory
DIR=/home/syounkin # Mine is in my home directory
mkdir -p $DIR/Vargo/log
mkdir -p $DIR/Vargo/DataScraper/data
mkdir -p $DIR/Vargo/DataScraper/html
cd $DIR/Vargo/DataScraper/
make MGE &>> $DIR/Vargo/log/make.log
