<<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Primary DataScraper Vignette}
-->

<link href="http://kevinburke.bitbucket.org/markdowncss/markdown.css" rel="stylesheet"></link>
<link href="http://www.biostat.wisc.edu/~syounkin/markdown_modified.css" rel="stylesheet"></link>

# DataScraper

## Load Libraries

```{r DataScraper, message=FALSE}
library("DataScraper")
#library("dplyr")
library("XML")
require("parallel")
getwd()
date()
set.seed(1)
```

### Importing Assessor Property Information for Madison

```{r input, eval = TRUE}
prop_info <- read.csv(file = "~/Dropbox/Vargo/data/energyTables/Assessor_Property_Information.csv", header=T, sep = ",", stringsAsFactors = FALSE)
```

```{r summary}
table(as.character(lapply(prop_info, class)))
```

###  Expand Address field to be multiple fields
```{r expand}
prop_info_expandedAddress <- expand_address(prop_info$Address)
names(prop_info_expandedAddress)
lapply(prop_info_expandedAddress, class)
```

Note that expand_address returns factors, not characters.  This could
cause bugs down the road.

```{r cat}
prop_info_expandedAddress <- cbind(prop_info, prop_info_expandedAddress)
```

###  Remove non residential property classes from the table & Remove
###  property with zero dwelling units


```{r non-residential}
prop_info_expandedAddress <- subset(prop_info_expandedAddress, Property.Class == "Residential")
prop_info_expandedAddress <- subset(prop_info_expandedAddress, Dwelling.Units > 0)
```

```{r sgy}
date()
Active_Address_List <- prop_info_expandedAddress

root_url <- "http://www.mge.com/customer-service/home/average-use-cost/results.htm?"

(timestamp <- gsub("\\s|:","-",Sys.time()))

energy.table.list <- list()

n <- 100
for( i in 1:n ){
#for( i in 1:nrow(Active_Address_List) ){

  house_number<-Active_Address_List$Address_Num[i]   # set house number
  street_direction<-Active_Address_List$Address_StreetDirection[i]   #set sd
  street_name<-Active_Address_List$Address_StreetName[i]   #set street name
  street_suffix<-Active_Address_List$Address_StreetType[i]   #set street suffix/Type
  apartment_unit<-Active_Address_List$Address_UnitNum[i]   #set au
  city<-"Madison"
  
  full_mge_url<-paste(sep="",root_url,"hn=",house_number,"&sd=",street_direction,"&sn=",street_name,"&ss=",street_suffix,"&au=",apartment_unit,"&c=",city)

  energy_table <- try(readHTMLTable(full_mge_url,as.data.frame=F), silent=TRUE)

  energy.table.list <- c(energy.table.list, energy_table)

}

names(energy.table.list) <- as.character(Active_Address_List$Parcel)[1:n]
## names(energy.table.list) <- as.character(Active_Address_List$Parcel)

saveRDS(energy.table.list, file = paste("~/Dropbox/Vargo/data/energyTables/energy.table.list-", timestamp, ".rds", sep = ""))

date()

```

```{r test2, error = FALSE, warning = FALSE}
parsedEnergyList <- mclapply(energy.table.list, parseEnergyTable,mc.cores = 8)
```

```{r test3, error = FALSE, warning = FALSE}
therms.NA <- unlist(lapply(parsedEnergyList,function(x)is.na(x$therms)||is.na(x$kWh)))
NAIndex <- which(therms.NA)
failureIndex <- which(unlist(lapply(parsedEnergyList,function(x)length(x)==0)))
1 - length(failureIndex)/length(parsedEnergyList)
```

```{r energyFile}
energy.df <- reshapeEnergyTableList(parsedEnergyList,paste("~/Dropbox/Vargo/data/energyTables/energyFile-",timestamp,sep=""))
head(energy.df)
```

```{r badIndex}
energy.df[failureIndex,]
```

```{r session}
sessionInfo()
```
