<<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Primary DataScraper Vignette}
-->

<link href="http://kevinburke.bitbucket.org/markdowncss/markdown.css" rel="stylesheet"></link>
<link href="http://www.biostat.wisc.edu/~syounkin/markdown_modified.css" rel="stylesheet"></link>

# DataScraper

## Load Libraries

```{r DataScraper, message=FALSE}
library("DataScraper")
getwd()
date()
set.seed(1)
```

```{r input, eval = TRUE}
data <- readRDS(file="~/Dropbox/Vargo/data/energyTables/energy.table.list-2015-05-08.rds")
```
```{r test2, error = FALSE, warning = FALSE}
parsedEnergyList <- lapply(data, parseEnergyTable)
names(parsedEnergyList) <- paste("Prop",1:length(parsedEnergyList), sep = "")
head(parsedEnergyList,2)
```

```{r test3, error = FALSE, warning = FALSE}
therms.NA <- unlist(lapply(parsedEnergyList,function(x)is.na(x$therms)||is.na(x$kWh)))
NAIndex <- which(therms.NA)
length(NAIndex)

failureIndex <- which(unlist(lapply(parsedEnergyList,function(x)length(x)==0)))
length(failureIndex)
length(parsedEnergyList)

1 - length(failureIndex)/length(parsedEnergyList)

```

```{r read}
propertyInfo <- read.csv(file = "~/Dropbox/Vargo/data/energyTables/Assessor_Property_Information.csv")
head(propertyInfo[failureIndex,c(2,4)],25)
```

```{r hist}
therms.average <- unlist(lapply(parsedEnergyList, function(x) x$therms[3]))
summary(therms.average)
```
